//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 1.102.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;

namespace FS.Abp.Themes.Core.Dtos
{
    public partial class WebsiteOptionsDto
    {
        public string Title { get; set; }

        public string Description { get; set; }

    }
    public partial class WebsiteOptionsWithDetailsDto : WebsiteOptionsDto
    {
    }
}
