//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 1.102.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Microsoft.EntityFrameworkCore;
using Volo.Abp;
namespace FS.Abp.Themes.EntityFrameworkCore
{
    public static class ThemesDbContextModelCreatingExtensions
    {
        public static void ConfigureThemes(
            this ModelBuilder builder,
            Action<ThemesModelBuilderConfigurationOptions> optionsAction = null)
        {
            Check.NotNull(builder, nameof(builder));

            var options = new ThemesModelBuilderConfigurationOptions(
                ThemesDbProperties.DbTablePrefix,
                ThemesDbProperties.DbSchema
            );

            optionsAction?.Invoke(options);

            builder.Ignore<FS.Abp.Themes.Core.WebsiteOptions>();
            builder.Ignore<FS.Abp.Themes.Core.LoginPageOptions>();
        }
    }
}
