//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating AbpSettings.
// 1.102.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Localization;
using Volo.Abp.Options;
using Volo.Abp.Settings;
using Volo.Abp.Threading;
using FS.Abp.Themes.Localization;


namespace FS.Abp.Themes.Core
{
    public partial class ThemesSettingNames
    {
        public partial class LoginPageOptions
        {
            private const string Prefix = "FS.Abp.Themes.Core.LoginPageOptions";
            public const string Title = Prefix + ".Title";
            public const string Description = Prefix + ".Description";
            public const string Footer = Prefix + ".Footer";
        }
    }
    public partial class LoginPageOptionsSettingDefinitionProvider : SettingDefinitionProvider
    {
        public override void Define(ISettingDefinitionContext context)
        {
            context.Add(
                        new SettingDefinition(ThemesSettingNames.LoginPageOptions.Title, @"LoginPage.Title", L("DisplayName:LoginPageOptions.Title"), L("Description:LoginPageOptions.Title"), true).WithProperty("Type","String"),
                        new SettingDefinition(ThemesSettingNames.LoginPageOptions.Description, @"LoginPage.Description", L("DisplayName:LoginPageOptions.Description"), L("Description:LoginPageOptions.Description"), true).WithProperty("Type","String"),
                        new SettingDefinition(ThemesSettingNames.LoginPageOptions.Footer, @"LoginPage.Footer", L("DisplayName:LoginPageOptions.Footer"), L("Description:LoginPageOptions.Footer"), true).WithProperty("Type","String")
                        );
        }
        private static LocalizableString L(string name)
        {
            return LocalizableString.Create<ThemesResource>(name);
        }
    }
    public partial class LoginPageOptionsFactory : AbpOptionsFactory<LoginPageOptions>
    {
        private readonly ISettingProvider _settingProvider;


        public LoginPageOptionsFactory(
            IEnumerable<IConfigureOptions<LoginPageOptions>> setups,
            IEnumerable<IPostConfigureOptions<LoginPageOptions>> postConfigures,
            ISettingProvider settingProvider)
            : base(setups, postConfigures)
        {
            _settingProvider = settingProvider;
        }

        public override LoginPageOptions Create(string name)
        {
            var options = base.Create(name);

            OverrideOptions(options);

            return options;
        }

        protected virtual void OverrideOptions(LoginPageOptions options)
        {
            AsyncHelper.RunSync(() => OverrideOptionsAsync(options));
        }

        protected virtual async Task OverrideOptionsAsync(LoginPageOptions options)
        {
            options.Title = await _settingProvider.GetOrNullAsync(ThemesSettingNames.LoginPageOptions.Title);
            options.Description = await _settingProvider.GetOrNullAsync(ThemesSettingNames.LoginPageOptions.Description);
            options.Footer = await _settingProvider.GetOrNullAsync(ThemesSettingNames.LoginPageOptions.Footer);
        }
    }
}
