//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating AbpSettings.
// 1.102.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Localization;
using Volo.Abp.Options;
using Volo.Abp.Settings;
using Volo.Abp.Threading;
using FS.Abp.Themes.Localization;


namespace FS.Abp.Themes.Core
{
    public partial class ThemesSettingNames
    {
        public partial class WebsiteOptions
        {
            private const string Prefix = "FS.Abp.Themes.Core.WebsiteOptions";
            public const string Title = Prefix + ".Title";
            public const string Description = Prefix + ".Description";
        }
    }
    public partial class WebsiteOptionsSettingDefinitionProvider : SettingDefinitionProvider
    {
        public override void Define(ISettingDefinitionContext context)
        {
            context.Add(
                        new SettingDefinition(ThemesSettingNames.WebsiteOptions.Title, @"Website.Title", L("DisplayName:WebsiteOptions.Title"), L("Description:WebsiteOptions.Title"), true).WithProperty("Type","String"),
                        new SettingDefinition(ThemesSettingNames.WebsiteOptions.Description, @"Website.Description", L("DisplayName:WebsiteOptions.Description"), L("Description:WebsiteOptions.Description"), true).WithProperty("Type","String")
                        );
        }
        private static LocalizableString L(string name)
        {
            return LocalizableString.Create<ThemesResource>(name);
        }
    }
    public partial class WebsiteOptionsFactory : AbpOptionsFactory<WebsiteOptions>
    {
        private readonly ISettingProvider _settingProvider;


        public WebsiteOptionsFactory(
            IEnumerable<IConfigureOptions<WebsiteOptions>> setups,
            IEnumerable<IPostConfigureOptions<WebsiteOptions>> postConfigures,
            ISettingProvider settingProvider)
            : base(setups, postConfigures)
        {
            _settingProvider = settingProvider;
        }

        public override WebsiteOptions Create(string name)
        {
            var options = base.Create(name);

            OverrideOptions(options);

            return options;
        }

        protected virtual void OverrideOptions(WebsiteOptions options)
        {
            AsyncHelper.RunSync(() => OverrideOptionsAsync(options));
        }

        protected virtual async Task OverrideOptionsAsync(WebsiteOptions options)
        {
            options.Title = await _settingProvider.GetOrNullAsync(ThemesSettingNames.WebsiteOptions.Title);
            options.Description = await _settingProvider.GetOrNullAsync(ThemesSettingNames.WebsiteOptions.Description);
        }
    }
}
